---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/distribution_centers":
    get:
      summary: show all distribution_centers
      tags:
      - Distribution Centers
      responses:
        '200':
          description: successful
  distribution_centers:
    post:
      summary: Create distribution_center
      tags:
      - Distribution Centers
      parameters: []
      responses:
        '201':
          description: distribution center was created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                latitude_location:
                  type: number
                longitude_location:
                  type: number
                total_space:
                  type: number
                available_space:
                  type: number
              required:
              - address
              - latitude_location
              - longitude_location
              - total_space,available_space
  "/distribution_centers/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show distribution_center
      tags:
      - Distribution Centers
      responses:
        '200':
          description: successful
    put:
      summary: update distribution_center
      tags:
      - Distribution Centers
      parameters: []
      responses:
        '201':
          description: distribution center was updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                latitude_location:
                  type: number
                longitude_location:
                  type: number
                total_space:
                  type: number
                available_space:
                  type: number
              required:
              - address
              - latitude_location
              - longitude_location
              - total_space,available_space
    delete:
      summary: delete distribution_center
      tags:
      - Distribution Centers
      responses:
        '200':
          description: successful
  "/time_schedules":
    get:
      summary: show all time_schedules
      tags:
      - Time Schedules
      responses:
        '200':
          description: successful
    post:
      summary: Create time_schedule
      tags:
      - Time Schedules
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                distribution_center_id:
                  type: integer
              required:
              - title
              - description
              - distribution_center_id
  "/time_schedules/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show time_schedule
      tags:
      - Time Schedules
      responses:
        '200':
          description: successful
    put:
      summary: Update time_schedule
      tags:
      - Time Schedules
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                distribution_center_id:
                  type: integer
              required:
              - distribution_center_id
    delete:
      summary: delete time_schedule
      tags:
      - Time Schedules
      responses:
        '200':
          description: successful
  "/time_windows":
    get:
      summary: show all time_windows
      tags:
      - Time Windows
      responses:
        '200':
          description: successful
    post:
      summary: 'create time_window '
      tags:
      - Time Windows
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                beginning:
                  type: string
                ending:
                  type: string
                time_schdule_id:
                  type: integer
              required:
              - beginning
              - ending
              - time_schdule_id
  "/time_windows/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show time_window
      tags:
      - Time Windows
      responses:
        '200':
          description: successful
    delete:
      summary: delete time_window
      tags:
      - Time Windows
      responses:
        '200':
          description: successful
  "/time_windows/everyday":
    post:
      summary: create a set of time windows repeating everyday
      tags:
      - Time Windows
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                year1:
                  type: integer
                month1:
                  type: integer
                day1:
                  type: integer
                year2:
                  type: integer
                month2:
                  type: integer
                day2:
                  type: integer
                daily_hours_list:
                  type: array
                  items:
                    type: array
                    items: 
                      type: array
                      items:
                        type: integer
                      minItems: 2
                      maxItems: 2
                    minItems: 2
                    maxItems: 2
                time_schedule_id:
                  type: integer
              required:
              - year1
              - month1
              - day1
              - year2
              - month2
              - day2
              - daily_hours_list
              - time_schedule_id
  "/time_windows/one_day_weekly_schedule":
    post:
      summary: 'create time windows repeating every selected ith day (Monday,...,Sunday) '
      tags:
      - Time Windows
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                year1:
                  type: integer
                month1:
                  type: integer
                day1:
                  type: integer
                year2:
                  type: integer
                month2:
                  type: integer
                day2:
                  type: integer
                daily_hours_list:
                  type: array
                  items:
                    type: array
                    items: 
                      type: array
                      items:
                        type: integer
                      minItems: 2
                      maxItems: 2
                    minItems: 2
                    maxItems: 2
                time_schedule_id:
                  type: integer
                week_day:
                  type: string
              required:
              - year1
              - month1
              - day1
              - year2
              - month2
              - day2
              - daily_hours_list
              - time_schedule_id
              - week_day
  "/time_windows/everyday_work_day":
    post:
      summary: create a set of time windows repeating from monday to friday
      tags:
      - Time Windows
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                year1:
                  type: integer
                month1:
                  type: integer
                day1:
                  type: integer
                year2:
                  type: integer
                month2:
                  type: integer
                day2:
                  type: integer
                daily_hours_list:
                  type: array
                  items:
                    type: array
                    items: 
                      type: array
                      items:
                        type: integer
                      minItems: 2
                      maxItems: 2
                    minItems: 2
                    maxItems: 2
                time_schedule_id:
                  type: integer
              required:
              - year1
              - month1
              - day1
              - year2
              - month2
              - day2
              - daily_hours_list
              - time_schedule_id
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
